version: '3.4'
services:
  assets:
    build:
      context: docker/assets
      network: host
    volumes:
    - ./web:/web
    working_dir: /web/assets
    command: "webpack --watch"
    tty: true
    networks:
    - hotel
  web:
    build: docker/python
    image: hotel/python
    ports:
    - ${WEB_PORT}:8080
    volumes:
    - ./web:/srv/app
    depends_on:
    - agent
    networks:
    - hotel
  agent:
    build: docker/php
    container_name: hotels-agent
    working_dir: /agent
    environment:
      - DB_HOST=db
      - DB_NAME_MAIN=main
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - HOTELS_NODES=krakow:${HOTEL_KRAKOW_PORT}|wroclaw:${HOTEL_WROCLAW_PORT}|gdansk:${HOTEL_GDANSK_PORT}
      - NGINX_HOST=nginx
      - QUEUE_HOST=queue
      - QUEUE_PORT=5672
      - QUEUE_USER=${QUEUE_USER}
      - QUEUE_PASS=${QUEUE_PASS}
    volumes:
      - ./agent:/agent
      - ./docker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    depends_on:
    - queue
    - hotel_krakow
    - hotel_wroclaw
    - hotel_gdansk
    - db
    networks:
    - hotel
  worker:
    build: docker/php
    container_name: hotels-worker
    working_dir: /worker
    command: "./yii reservation-handler"
    environment:
      - DB_HOST=db
      - DB_NAME_MAIN=main
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - HOTELS_NODES=krakow:${HOTEL_KRAKOW_PORT}|wroclaw:${HOTEL_WROCLAW_PORT}|gdansk:${HOTEL_GDANSK_PORT}
      - NGINX_HOST=nginx
      - QUEUE_HOST=queue
      - QUEUE_PORT=5672
      - QUEUE_USER=${QUEUE_USER}
      - QUEUE_PASS=${QUEUE_PASS}
    volumes:
      - ./worker:/worker
      - ./docker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    depends_on:
      - queue
      - hotel_krakow
      - hotel_wroclaw
      - hotel_gdansk
      - db
    networks:
      - hotel
  queue:
    image: rabbitmq:3.7.4-management-alpine
    ports:
    - ${QUEUE_PORT}:5672
    - ${QUEUE_GUI_PORT}:15672
    environment:
    - RABBITMQ_DEFAULT_USER=${QUEUE_USER}
    - RABBITMQ_DEFAULT_PASS=${QUEUE_PASS}
    networks:
    - hotel
  redis:
    image: redis:alpine
    container_name: hotels-redis
    networks:
      - hotel
  db:
    image: mysql:5.7.23
    container_name: hotels-db
    ports:
      - ${DB_PORT}:3306
    volumes:
    - hotel_db_data:/var/lib/mysql
    - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
    - hotel
  nginx:
    image: nginx:alpine
    container_name: hotels-nginx
    volumes:
      - ./hotel:/hotel
      - ./agent:/agent
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${HOTEL_KRAKOW_PORT}:8201
      - ${HOTEL_WROCLAW_PORT}:8202
      - ${HOTEL_GDANSK_PORT}:8203
      - ${AGENT_PORT}:8101
    networks:
      - hotel
  hotel_krakow:
    build: docker/php
    container_name: hotels-hotel_krakow
    working_dir: /hotel
    environment:
      - DB_HOST=db
    env_file:
      - ./hotel_krakow.env
    volumes:
      - ./hotel:/hotel
      - ./docker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    depends_on:
      - db
    networks:
      - hotel
  hotel_wroclaw:
    build: docker/php
    container_name: hotels-hotel_wroclaw
    working_dir: /hotel
    environment:
      - DB_HOST=db
    env_file:
      - ./hotel_wroclaw.env
    volumes:
      - ./hotel:/hotel
      - ./docker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    networks:
    - hotel
  hotel_gdansk:
    build: docker/php
    container_name: hotels-hotel_gdansk
    working_dir: /hotel
    environment:
      - DB_HOST=db
    env_file:
      - ./hotel_gdansk.env
    volumes:
      - ./hotel:/hotel
      - ./docker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    networks:
    - hotel
networks:
  hotel:
volumes:
  hotel_db_data:
